### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by Gattomarino** [SkepticMystic/breadcrumbs#383]
I was about to experiment with a new "up" name and after I changed it in the preferences, the plugin stopped showing me data in the matrix view. Two errors popped up in the console:
`
VM159:35173 TypeError: arr.join is not a function
    at MatrixView.getAlt (eval at <anonymous> (app.js:1:1494667), <anonymous>:35044:49)
    at MatrixView.toInternalLinkObj (eval at <anonymous> (app.js:1:1494667), <anonymous>:34987:27)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:35086:41)
    at Array.map (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:35086:22)
    at Array.map (<anonymous>)
    at MatrixView.getHierSquares (eval at <anonymous> (app.js:1:1494667), <anonymous>:35075:26)
    at MatrixView.draw (eval at <anonymous> (app.js:1:1494667), <anonymous>:35165:38)
    at refreshIndex (eval at <anonymous> (app.js:1:1494667), <anonymous>:34082:94)
    at async Object.saveCommandDefinition.callback (eval at <anonymous> (app.js:1:1494667), <anonymous>:62427:25)
draw @ VM159:35173
refreshIndex @ VM159:34082
await in refreshIndex (async)
saveCommandDefinition.callback @ VM159:62427
await in saveCommandDefinition.callback (async)
Mz @ app.js:1
e.executeCommandById @ app.js:1
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1

VM159:35173 TypeError: arr.join is not a function
    at MatrixView.getAlt (eval at <anonymous> (app.js:1:1494667), <anonymous>:35044:49)
    at MatrixView.toInternalLinkObj (eval at <anonymous> (app.js:1:1494667), <anonymous>:34987:27)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:35086:41)
    at Array.map (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:35086:22)
    at Array.map (<anonymous>)
    at MatrixView.getHierSquares (eval at <anonymous> (app.js:1:1494667), <anonymous>:35075:26)
    at MatrixView.draw (eval at <anonymous> (app.js:1:1494667), <anonymous>:35165:38)
    at Object.saveCommandDefinition.callback (eval at <anonymous> (app.js:1:1494667), <anonymous>:62430:46)
draw @ VM159:35173
saveCommandDefinition.callback @ VM159:62430
await in saveCommandDefinition.callback (async)
Mz @ app.js:1
e.executeCommandById @ app.js:1
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
`

**Comment by SkepticMystic** [comment]
Does this still happen for you?

**Comment by Gattomarino** [comment]
I can't reproduce the issue anymore, it seems to work just fine.

Il giorno sab 13 gen 2024 alle ore 22:21 SkepticMystic <
***@***.***> ha scritto:

**Comment by SkepticMystic** [comment]
Alright, thanks for letting me know. I'll close it out for now
